// src/main/Frontend/src/components/Nutrition.tsx
'use client'
import InfoBlock from './/InfoBlock'
import React, {useState, useEffect, useRef} from 'react'
import axios from 'axios'

function toTitleCase(str) {
    return str.replace(/\w\S*/g, function (txt) {
        return txt.charAt(0).toUpperCase() + txt.substr(1).toLowerCase();
    });
}

function Nutrition() {
    const [querySearch, setQuerySearch] = useState('')
    const [searchedRecipes, setSearchedRecipes] = useState([])
    const [recipes, setRecipes] = useState([])
    const [recommendedRecipes, setRecommendedRecipes] = useState([])
    const recipeRef = useRef();
    useEffect(() => {
        axios.get('/api/v1/recipes/10').then(res => {
            console.log(res.data)
            let data = res.data.filter(item => item.imgSrc !== null)
            let arr = []
            for (let i = 0; i < data.length; i += 3) {
                let newArr = []
                for (let j = 0; j < 3; j++) newArr.push(data[i + j])
                arr.push(newArr)
            }
            setRecipes(arr)
        }).catch(err => {
            console.log(err)
        })
    }, [])
    const recipeComponents = recipes.map((item: any[]) => {
        let data = item.filter(val => val != null);
        return (<div className='row'> {data.map((elementLis, idx) => (
            <InfoBlock key={idx} heading={elementLis.name} bg='bg-info' icon={elementLis.imgSrc} text={[
                <div>{elementLis.duration}</div>,
                <div>Rating: {elementLis.rating}</div>
            ]}/>))} </div>);
    });


    async function getQuery(query) {
        if (query === '') {

            setQuerySearch('')
            setSearchedRecipes([])
            return
        }
        setQuerySearch(query)
        try {
            let promise = await axios.post(`/api/v1/recipes/${query.toLowerCase()}`)
            setSearchedRecipes(promise.data)
        } catch {
            setSearchedRecipes([])
        }
    }

    useEffect(() => {
        getQuery(querySearch)
    }, [querySearch]);
    // Here you can place your asynchronous logic (like ajax calls)

    // function getFormData(object: {}) {
    //     const formData = new FormData();
    //     formData.append('ingredients', JSON.stringify(object));
    //     return formData;
    // }

    return (
        <>
            <div className='lowPoly heroback py-5 container-fluid align-content-center'>
                <div style={{height: '30px'}}>
                </div>
                <h1 className='text-info py-5 text-center'>Search for
                    Personalized Recipes shipped right to you door</h1>

                <div className='row justify-content-center '>
                    <div className='col-auto'>
                        <h4 className='text-info'>Recommend recipes</h4>
                    </div>
                    <div className="col-auto">
                        <input className="form-control border-danger border-4 mr-sm-2" id='navSearch' type="search"
                               placeholder="Search" value={querySearch}
                               onChange={(e) => {
                                   setQuerySearch(e.target.value);
                                   // getQuery(e.target.value)
                               }
                               }
                               aria-label="Search"/>
                        <ul className="list-group" style={{height: 200, overflow: 'scroll'}}>
                            {searchedRecipes.map((val, ind) => (<li onMouseOut={(ele) => {
                                ele.target.classList.remove('active')
                            }} onMouseEnter={(ele) => {
                                ele.target.classList.add('active')
                            }} onClick={(ele) => {
                                setQuerySearch(ele.target.innerText)
                            }} className='list-group-item' key={ind}>{toTitleCase(val.query)}</li>))}
                        </ul>
                    </div>

                    <div className="col-auto justify-content-center">
                        <button className="btn btn-lg btn-outline-danger my-2 my-sm-0" type="submit"
                                id='recipeSearch' onClick={() => {
                            axios.get(`/recommendations?query=${encodeURIComponent(querySearch)}`).then((res) => {
                                console.log(res.data)
                                setRecommendedRecipes(res.data)
                                // console.log(typeof(res.data))
                            })
                            // setQuerySearch(ele.target.innerHTML)
                        }}>Search
                        </button>

                    </div>
                </div>

                <div className='row'>
                    {Object.values(recommendedRecipes).map((val, index) => <div className='col-6'><InfoBlock key={index}
                                                                                                             heading={val['name']}
                                                                                                             bg='bg-danger'
                                                                                                             text={[val.duration, val.rating]}></InfoBlock>
                    </div>)}
                </div>
            </div>
            <div className='spacer waves3'></div>
            <div className="heroback layer2 container-fluid">

                <div className='row justify-content-center'>
                    <div className='col-auto'>
                        {/*<ul className="nav nav-pills bg-info rounded-3">*/}
                        {/*    <li className="nav-item">*/}
                        {/*        <a className="nav-link active" aria-current="page" href="#">Breakfast</a>*/}
                        {/*    </li>*/}
                        {/*    <li className="nav-item">*/}
                        {/*        <a className="nav-link" href="#">Lunch</a>*/}
                        {/*    </li>*/}
                        {/*    <li className="nav-item">*/}
                        {/*        <a className="nav-link" href="#">Easy Main Dish</a>*/}
                        {/*    </li>*/}
                        {/*    <li className="nav-item">*/}
                        {/*        <a className="nav-link" href="#">Hamburgers</a>*/}
                        {/*    </li>*/}
                        {/*    <li className="nav-item">*/}
                        {/*        <a className="nav-link" href="#">Healthy</a>*/}
                        {/*    </li>*/}
                        {/*    <li className="nav-item">*/}
                        {/*        <a className="nav-link" href="#">Desserts</a>*/}
                        {/*    </li>*/}
                        {/*    <li className="nav-item">*/}
                        {/*        <a className="nav-link disabled" href="#" tabIndex="-1"*/}
                        {/*           aria-disabled="true">Disabled</a>*/}
                        {/*    </li>*/}
                        {/*</ul>*/}
                        <form className='bg-danger rounded-3'>

                            <ul className="nav nav-pills bg-secondary rounded-3">
                                <li className="nav-item">
                                    <a className="nav-link active" aria-current="page" href="#">Anything</a>
                                </li>
                                <li className="nav-item">
                                    <a className="nav-link" href="#">Vegan</a>
                                </li>
                                <li className="nav-item">
                                    <a className="nav-link" href="#">Paleo</a>
                                </li>
                                <li className="nav-item">
                                    <a className="nav-link" href="#">Pescatarian</a>
                                </li>
                                <li className="nav-item">
                                    <a className="nav-link" href="#">Vegetarian</a>
                                </li>
                                <li className="nav-item">
                                    <a className="nav-link" href="#">Ketogenic</a>
                                </li>
                                <li className="nav-item">
                                    <a className="nav-link" href="#">Atkins</a>
                                </li>
                            </ul>

                            <legend className=''>Build Your own Diet</legend>
                            <label for='calories' className="p-3">Calories</label>
                            <input id='calories' type="number" className='rounded-2' placeholder='3000'/>
                        {/*
                        breakfast lunch dinner snacks desserts */}
                        </form>
                    </div>
                </div>
            </div>
            <div className='spacer waves2'></div>
            <div className='lowPoly3 heroback'>
                <div className='row' ref={recipeRef} style={{display: 'inline-flex'}}>
                    {recipeComponents}
                </div>
            </div>
        </>
    )
}


export default Nutrition

// main/frontend-svelte/src/routes/Nutrition/+page.svelte
<script>
    import { onMount } from 'svelte';
    import InfoBlock from '$lib/components/InfoBlock.svelte';
    import axios from 'axios';

    // State variables
    let querySearch = '';
    let searchedRecipes = [];
    let recipes = [];
    let searchedRecipe = null;
    let recommendedRecipes = [];

    // Helper function to convert string to title case
    function toTitleCase(str) {
        return str.replace(/\w\S*/g, function (txt) {
            return txt.charAt(0).toUpperCase() + txt.substr(1).toLowerCase();
        });
    }

    // Fetch initial recipes on component mount
    onMount(async () => {
        try {
            const res = await axios.get('/api/v1/recipes/10');
            console.log('Response data:', res.data);
            recipes = res.data;
        } catch (err) {
            console.log(err);
        }
    });

    // Search function
    async function getQuery(query) {
        if (query === '') {
            querySearch = '';
            searchedRecipes = [];
            return;
        }

        try {
            const promise = await axios.post(`/api/v1/recipes/${query.toLowerCase()}`);
            searchedRecipes = promise.data;
        } catch {
            searchedRecipes = [];
        }
    }

    // Watch for querySearch changes
    $: {
        getQuery(querySearch);
    }

    // Search recipe function
    async function searchRecipe() {
        console.log("Query: " + querySearch);
        console.log("Searched Recipe: " + searchedRecipe?.name);

        try {
            const res = await axios.get(`/api/v1/recipes/recipe/${encodeURIComponent(querySearch)}`);
            console.log(res.data);
            searchedRecipe = res.data;

            const recRes = await axios.get(`api/v1/recipes/recommendations?query=${encodeURIComponent(querySearch)}&ingredients=${res.data?.ingredients}`);
            console.log(recRes.data);
            recommendedRecipes = recRes.data;
        } catch (err) {
            console.error("Error fetching recipe:", err);
        }
    }

    // Clear function
    function clearSearch() {
        recommendedRecipes = [];
        querySearch = '';
        searchedRecipe = null;
    }
</script>

<div class='heroback py-8 w-full mx-auto' id='nutrition-header'>
    <div class="h-16"></div>
    <h1 class='text-primary font-orbital font-bold text-4xl py-5 my-5 text-center'>Search for Personalized Recipes shipped right to your door</h1>

    <h3 class="text-primary text-3xl font-orbital font-bold text-center">Search for recipes from our personalized catalogue</h3>

    <!-- Recipe Components -->
    <div class="wrapper w-full">
        {#each recipes as recipe, index}
            <div class={`item item${index + 1}`} >
                <InfoBlock
                        title={recipe.name}
                        headingClass="text-gray-800 text-2xl text-center font-orbital font-bold"
                        text={[
                        recipe.duration ? `Duration: ${recipe.duration}` : "",
                        recipe.rating ? `Rating: ${recipe.rating}` : "",
                    ]}
                        recipe={recipe}
                        fadeInAnimation="fadeIn"
                        bg="bg-[#3E92CC]"
                        expandable={true}
                />
            </div>
        {/each}
    </div>

    <div class='bg-info w-full max-w-xl mx-auto' style="
        border: 1rem solid rgba(0, 255, 255, .5);
        box-shadow: 8px 8px 3px rgba(0, 255, 125, 1);
        padding: 20px;
        border-radius: 2px;
    ">
        <h2 class='text-primary text-3xl font-orbital font-bold py-8 text-center'>Recommend recipes</h2>

        {#if searchedRecipe !== null}
            <InfoBlock
                    bg='bg-[#faebd7] w-1/3'
                    title={searchedRecipe.name}
                    headingClass="text-gray-800 text-2xl font-orbital font-bold text-center"
                    recipe={searchedRecipe}
                    text={[]}
                    expandable={true}
            />
        {/if}

        <div class='flex justify-center rounded-md'>
            <div class='w-1/2 flex justify-between'>
                <button
                        class="w-1/2 text-lg border border-primary text-primary hover:bg-primary hover:text-black my-2 mx-1 py-2 px-4 rounded-md transition-all"
                        type="submit"
                        id='recipeSearch'
                        on:click={searchRecipe}>
                    Search
                </button>
                <button
                        class="w-1/2 text-lg border border-primary text-primary hover:bg-primary hover:text-black my-2 mx-1 py-2 px-4 rounded-md transition-all"
                        type="submit"
                        id='clear'
                        on:click={clearSearch}>
                    Clear
                </button>
            </div>
        </div>

        <div class='flex justify-center'>
            <div class='w-1/2 mb-3'>
                <input
                        class="w-full p-2 border-4 border-[#00A76E] bg-amber-50 rounded focus:outline-none focus:ring focus:ring-[#C62368] focus:border-[#C62368]"
                        id='navSearch'
                        type="search"
                        placeholder="Search"
                        bind:value={querySearch}
                        aria-label="Search"
                />
            </div>
        </div>
    </div>

    {#if searchedRecipes.length > 0}
        <div class='flex justify-center'>
            <div class='w-1/2'>
                <ul class="bg-white border-primary rounded-lg border border-gray-200 divide-y divide-gray-200">
                    {#each searchedRecipes as val, ind}
                        <li
                                on:mouseout={(ele) => {
                                ele.target.classList.remove('bg-gray-100')
                            }}
                                on:mouseenter={(ele) => {
                                ele.target.classList.add('bg-gray-100')
                            }}
                                on:click={(ele) => {
                                querySearch = ele.target.innerText
                            }}
                                class='px-4 py-2 cursor-pointer'>
                            {toTitleCase(val.query)}
                        </li>
                    {/each}
                </ul>
            </div>
        </div>
    {/if}

    {#if recommendedRecipes.length !== 0}
        <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-5 justify-center">
            {#each recommendedRecipes as recipe, index}
                <div class="flex justify-center">
                    <InfoBlock
                            title={recipe.name}
                            headingClass="text-gray-800 text-2xl font-orbital font-bold text-center"
                            text={[
                            recipe.duration ? `Duration: ${recipe.duration}` : "",
                            recipe.rating ? `Rating: ${recipe.rating}` : "",
                        ]}
                            recipe={recipe}
                            fadeInAnimation="fadeIn"
                            bg="bg-info"
                            expandable={true}
                    />
                </div>
            {/each}
        </div>
    {/if}
</div>
